### PR TITLE
readme: update troubleshooting related to ca-certificates on MacOS

### PR DESCRIPTION
**Pull request by rsrohitsingh682**
Add troubleshooting doc for ca-ceritificates on MacOS while initialising the template.

### CODE REVIEW

**Review by srid — CHANGES_REQUESTED** [review]
Could you fix the monospace rendering?

image

**Comment by srid** [comment]
Please also link to the upstream issue if any.

**Comment by rsrohitsingh682** [comment]
> Please also link to the upstream issue if any.

Not an active issue. This happens generally when there is a broken symbolic link, probably from previous nix-darwin installation.

**Comment by srid** [comment]
> > Please also link to the upstream issue if any.
> 
> Not an active issue. This happens generally when there is a broken symbolic link, probably from previous nix-darwin installation.

Link to https://github.com/NixOS/nix/issues/2899#issuecomment-1669501326

**Comment by srid** [comment]
Rendering is still broken,

image

**Comment by srid** [comment]
"Problem" and "Solution" spacing is also broken, compared to the other item.

**Pull request merged**
